version: "3.7"
services:
  jellyfin:
    image: crazygit/jellyfin
    restart: unless-stopped
    ports:
      - 5800:5800
      - 5900:5900
    network_mode: host
    user: ${PUID}:${PGID}
    volumes:
      - jellyfin_config_volume:/config
      - jellyfin_cache_volume:/cache
      - jellyfin_media_volume:/media

  tiny_media_manager:
    image: romancin/tinymediamanager
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
    ports:
      - 5800:5800
      - 5900:5900
    volumes:
      - tiny_media_manager_config_volume:/config
      - jellyfin_media_volume:/media

  aria2_pro:
    image: p3terx/aria2-pro
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - RPC_SECRET=${ARIA2_PRC_SECRET}
    ports:
      - 6800:6800
      - 9888:6888
      - 6888:6888/udp
    volumes:
      - aria2_pro_config_volume:/config
      - aria2_pro_downloads_volume:/downloads

  aria_ng:
    image: crazygit/aria_ng
    ports:
      - 80:80

  samba:
    image: dperson/samba
    restart: unless-stopped
    environment:
      - USERID=${PUID}
      - GROUPID=${PGID}
    ports:
      - 139:139
      - 445:445
    volumes:
      - jellyfin_media_volume:/mount
    command: ["-p", "-u", "samba_user;samba_password", "-s", "media share;/mount;yes;no;yes"]
    # -u 设置samba的用户名和密码，用";"分隔
    # -s 设置samba的分享路径
    # https://hub.docker.com/r/dperson/samba/
    # -s选项的使用格式
    #    -s "<name;/path>[;browse;readonly;guest;users;admins;writelist;comment]"
    #                Configure a share
    #                required arg: "<name>;</path>"
    #                <name> is how it's called for clients
    #                <path> path to share
    #                NOTE: for the default values, just leave blank
    #                [browsable] default:'yes' or 'no'
    #                [readonly] default:'yes' or 'no'
    #                [guest] allowed default:'yes' or 'no'
    #                NOTE: for user lists below, usernames are separated by ','
    #                [users] allowed default:'all' or list of allowed users
    #                [admins] allowed default:'none' or list of admin users
    #                [writelist] list of users that can write to a RO share
    #                [comment] description of share

  kodi_headless:
    image: linuxserver/kodi-headless
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    ports:
      - 8080:8080
      - 9090:9090
      - 9777:9777/udp
    volumes:
      - kodi_config_volume:/config/.kodi

volumes:
  jellyfin_config_volume:
    driver: local
    driver_opts:
      type: none
      device: /data/service/jellyfin/config
      o: bind

  jellyfin_cache_volume:
    driver: local
    driver_opts:
      type: none
      device: /data/service/jellyfin/cache
      o: bind

  jellyfin_media_volume:
    driver: local
    driver_opts:
      type: none
      device: /data/service/jellyfin/media
      o: bind

  tiny_media_manager_config_volume:
    driver: local
    driver_opts:
      type: none
      device: /data/service/tiny_media_manager/config
      o: bind

  aria2_pro_config_volume:
    driver: local
    driver_opts:
      type: none
      device: /data/service/aria2/config
      o: bind

  aria2_pro_downloads_volume:
    driver: local
    driver_opts:
      type: none
      device: /data/service/aria2/downloads
      o: bind

  kodi_config_volume:
    driver: local
    driver_opts:
      type: none
      device: /data/service/kodi/config
      o: bind

